### ISSUE TITLE
[1.10.2] Infusion Ritual for Enchanted Book not Working

### ISSUE THREAD

**Issue by Alan19** [Shinoow/AbyssalCraft-Integration#12]
I'm using `mods.abyssalcraft.InfusionRitual.addRitual("sharpnessRitual", 2, 53, 800, false, <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 8 as short, id: 16 as short}]}), <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 7 as short, id: 16 as short}]}), [<botania:manaResource:4>, <bloodmagic:ItemActivationCrystal>, <evilcraft:invertedPotentia:1>, <botania:overgrowthSeed>, <abyssalcraft:platec>, <astralsorcery:ItemShiftingStar>], true);` to add an infusion recipe to upgrade a sharpness 7 book into a sharpness 8 book but it's telling me that my data types do not match with the available methods because I have an int for the potential energy required but there's no problem with the example dirt to diamonds recipe.

**Comment by Shinoow** [comment]
It seems to completely refuse to recognize the method with the nbt parameter as long as there's one with yet another parameter. Until I find a solution for this (either set up bracket handlers for rituals, or switch them over to properly specifying optional parameters), you'll have to supply an empty array at the end (just ```[]```).

**Comment by Alan19** [comment]
Thanks! I managed to fix the script!
