### ISSUE TITLE
[1.12.2][Bug] Tinkerer's Construct Parts missing color

### ISSUE THREAD

**Issue by Mike-T4** [Shinoow/AbyssalCraft-Integration#13]
Tinkerer's Construct pars made out of Dreadium, Abyssalnite and Refined Coralium are all white rather than their usual colors.

**Comment by Shinoow** [comment]
I didn't look that far into this while throwing that port together, but there seems like something changed in the part where the color is set, seemingly ignoring the colors I've specified.
