### ISSUE TITLE
Unable to make infusion ritual output NBT data

### ISSUE THREAD

**Issue by monodemono** [Shinoow/AbyssalCraft-Integration#20]
#### Description:
Created a custom instance for testing.
Mods included:
AbyssalCraft 1.9.4.11
AbyssalCraft Integrations 1.6.5
Actually Additions r140 (just added this for the advanced tooltips functionality)
CraftTweaker 4.1.9_testC
JEI 4.11.0.212

- Minecraft: 1.12.2
- Forge: 14.23.4.2750

Here's my test script:
```
mods.abyssalcraft.InfusionRitual.addRitual("sword", 0, -1, 100, true, <minecraft:diamond_sword>.withTag({ench: [{lvl: 1 as short, id: 19 as short}, {lvl: 1 as short, id: 18 as short}], RepairCost: 0, display: {Name: "Necron's Fury"}}), <minecraft:diamond_sword>, [
		<minecraft:grass>, <minecraft:grass>,
		<minecraft:grass>, <minecraft:grass>, <minecraft:grass>,
		<minecraft:grass>, <minecraft:grass>, <minecraft:grass>
	], false, []);
game.setLocalization("ac.ritual.sword", "Sword Ritual");
game.setLocalization("ac.ritual.sword.desc", "This ritual enchants and names a diamond sword for testing.");
```

Client tweaker log has no errors.

As you can see, it's properly added:
<img width="1920" alt="screen shot 2018-08-15 at 14 17 29" src="https://user-images.githubusercontent.com/1161277/44173894-2882cf00-a096-11e8-94ce-c9d30f843845.png">

Properly setup:
<img width="1920" alt="screen shot 2018-08-15 at 14 18 02" src="https://user-images.githubusercontent.com/1161277/44173922-40f2e980-a096-11e8-8c27-053d7e9d27af.png">

Runs just fine:
<img width="1920" alt="screen shot 2018-08-15 at 14 18 13" src="https://user-images.githubusercontent.com/1161277/44173941-4fd99c00-a096-11e8-9620-beda31fb7079.png">

But in the end, the output failed...
<img width="1920" alt="screen shot 2018-08-15 at 14 18 35" src="https://user-images.githubusercontent.com/1161277/44173951-5b2cc780-a096-11e8-8e3f-e178c6c165a6.png">

And just for the sake of being thorough, here's a client log, but as you can see there's nothing relating to this issue there: https://gist.github.com/monodemono/48c9edc488bb7b75dda600153718ccf0

**Comment by Shinoow** [comment]
https://github.com/Shinoow/AbyssalCraft/commit/2bad695b74a601e47e8410788cf21c8b4d91140f
