### ISSUE TITLE
RemovePage does not actually remove page

### ISSUE THREAD

**Issue by Mike-U5** [Shinoow/AbyssalCraft-Integration#29]
Minecraft 1.12.2.
AbyssalCraft 1.9.6
AbyssalCraft Integration 1.8.1

The removePage minetweaker command does not actually remove a page form the Necronomicon, it just makes it empty. As a result, you are left with a bunch of blank pages if you try to remove some.

**Comment by Shinoow** [comment]
Fixed in [AbyssalCraft 1.9.7](https://minecraft.curseforge.com/projects/abyssalcraft/files/2704702).
