### ISSUE TITLE
Crash In Latest Version

### ISSUE THREAD

**Issue by NihilEntropy** [Shinoow/AbyssalCraft-Integration#32]
I'm not sure what causes this crash, as it happened when I installed it. And the crash report isn't obvious to me what happened. It doesn't seem to be a conflict.

#### Crash report:

https://pastebin.com/2FzGeEFf

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- AbyssalCraft Integration: AbyssalCraft+Integration-1.12.2-1.9.0
- AbyssalCraft: AbyssalCraft-1.12.2-1.9.10

#### Latest log file for when the issue was present:
[latest.log](https://github.com/Shinoow/AbyssalCraft-Integration/files/3479577/latest.log)
Linking file because its too large for pastebin

**Comment by Shinoow** [comment]
Update Bewitchment. AbyssalCraft Integration 1.9.0 supports Bewitchment 0.0.20, which included a big rewrite on their end, which makes the integration incompatible with earlier versions of that mod.

**Comment by NihilEntropy** [comment]
Got it.
