### ISSUE TITLE
[request] Option to set burn time/fuel value when adding materials to Crystal List.

### ISSUE THREAD

**Issue by CelestialPhoenix** [Shinoow/AbyssalCraft-Integration#33]
As per title, would it be possible to define a fuel value for powering the Crystallizer?
`mods.abyssalcraft.Materializer.addCrystal(IItemStack stack, optional int burntime);`

**Comment by Shinoow** [comment]
With that I might as well add a way to add Crystallizer and/or Transmutator fuels through CraftTweaker.
