### ISSUE TITLE
Progression in thaumcraft halted till you go to Abyss

### ISSUE THREAD

**Issue by Zectorian** [Shinoow/AbyssalCraft-Integration#34]
The copper ingot requirement for alchemical brass transmutation thaumcraft makes it impossible to progress in Thaumcraft unless you literally go to the abyss, that is a problem

**Comment by Shinoow** [comment]
This is outside of my control. Install a mod that adds copper ore to the overworld, or set something up with ContentTweaker and CoFH Worldgen (or something else that allows you to add ore generation, in case ContentTweaker doesn't have a thing built-in for that).
