### ISSUE TITLE
Wands Need Upgrades to Their Vis Capacities 

### ISSUE THREAD

**Issue by Alan19** [Shinoow/AbyssalCraft-Integration#5]
Wands using abyssalcraft materials have capacities balanced for TC4 and can't store Terra
![2016-07-31_15 25 23](https://cloud.githubusercontent.com/assets/11682762/17278779/23e7d6ec-5733-11e6-8f65-6bcb5e0eaacb.png)

**Comment by Shinoow** [comment]
There's probably a few more things that could use some re-balancing.

**Comment by Alan19** [comment]
This is on 1.8.9 by the way

**Comment by Shinoow** [comment]
Fixed in 1.4.6.
